<a href="https://colab.research.google.com/github/Nurdaylight/Study/blob/main/Tensorgym.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [50]:
z=torch.randint(0,2,(9,4))

In [51]:
z

tensor([[1, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 1, 1, 0],
        [1, 0, 0, 0]])

In [52]:
b = z <= 0
(b.float()).mean(1).max()

tensor(0.7500)

In [57]:
b = z==0
a=(b.float()).mean(0).max()
c = (b.float()).mean(0) ==a

result =z[:,c]

In [64]:
import torch

def drop_column(A: torch.tensor) -> torch.tensor:
    """
    Drops the column of A containing the most 0 values.

    Parameters:
        tensor: A 2D tensor.
    Returns:
        tensor: The input tensor with the column containing the most 0 values removed.
    """

    result = None
    b = A==0
    a=(b.float()).mean(0).max()
    z = (b.float()).mean(0)!=a

    result =A[:,z]
    return result

tensor reshaepe and transpoe

In [ ]:
import torch

def solution(x: torch.Tensor) -> torch.Tensor:
    '''
        x is one-dimentional tensor
    '''
    result = None
    n=len(x)
    result=x.view(-1,int(n/2)).T
    ###### your code here: #####
    return result

just every second row sum

In [66]:
a=torch.randn(8,6)

In [73]:
a[::2, :]

tensor([[-2.1132,  0.1264,  0.2206,  0.4287,  1.2419,  0.1991],
        [ 0.9447,  1.5673,  0.6037,  1.0576, -0.8645,  1.4010],
        [-2.5516,  1.1275,  0.2309, -0.0177,  1.3985,  1.3792],
        [ 1.5372, -1.3131,  1.4332, -0.1671,  0.8736, -1.5214]])

In [72]:
import torch

def solution(matrix: torch.Tensor) -> torch.Tensor:
    result = None
    ###### your code here: #####
    result= matrix[::2,:].float().sum(1)
    return result

tensor([[-2.1132,  0.1264,  0.2206,  0.4287,  1.2419,  0.1991],
        [-0.9465, -0.1765, -0.8215, -0.7511, -0.8301, -1.8387],
        [ 0.9447,  1.5673,  0.6037,  1.0576, -0.8645,  1.4010],
        [ 0.5191,  0.0555,  1.0875,  2.0034, -0.9926, -0.3154],
        [-2.5516,  1.1275,  0.2309, -0.0177,  1.3985,  1.3792],
        [ 0.8277,  1.3446, -0.3662, -0.3400,  0.7048, -0.5387],
        [ 1.5372, -1.3131,  1.4332, -0.1671,  0.8736, -1.5214],
        [ 0.9302, -0.2264,  0.8700,  0.9967,  2.0280, -0.0940]])

In [84]:
a.mean(1).argmax().item()

2

In [93]:
a.var(correction=0)

tensor(1.1594)

In [94]:
((a-a.mean())**2).mean()

tensor(1.1594)

In [ ]:
data=((data-data.mean())**2).mean()