<a href="https://colab.research.google.com/github/Nurdaylight/Study/blob/main/Tensorgym.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
z=torch.randint(0,2,(9,4))

In [ ]:
z

tensor([[1, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 1, 1, 0],
        [1, 0, 0, 0]])

In [ ]:
b = z <= 0
(b.float()).mean(1).max()

tensor(0.7500)

In [ ]:
b = z==0
a=(b.float()).mean(0).max()
c = (b.float()).mean(0) ==a

result =z[:,c]

In [ ]:
import torch

def drop_column(A: torch.tensor) -> torch.tensor:
    """
    Drops the column of A containing the most 0 values.

    Parameters:
        tensor: A 2D tensor.
    Returns:
        tensor: The input tensor with the column containing the most 0 values removed.
    """

    result = None
    b = A==0
    a=(b.float()).mean(0).max()
    z = (b.float()).mean(0)!=a

    result =A[:,z]
    return result

tensor reshaepe and transpoe

In [ ]:
import torch

def solution(x: torch.Tensor) -> torch.Tensor:
    '''
        x is one-dimentional tensor
    '''
    result = None
    n=len(x)
    result=x.view(-1,int(n/2)).T
    ###### your code here: #####
    return result

just every second row sum

In [ ]:
a=torch.randn(8,6)

In [ ]:
a[::2, :]

tensor([[-2.1132,  0.1264,  0.2206,  0.4287,  1.2419,  0.1991],
        [ 0.9447,  1.5673,  0.6037,  1.0576, -0.8645,  1.4010],
        [-2.5516,  1.1275,  0.2309, -0.0177,  1.3985,  1.3792],
        [ 1.5372, -1.3131,  1.4332, -0.1671,  0.8736, -1.5214]])

In [ ]:
import torch

def solution(matrix: torch.Tensor) -> torch.Tensor:
    result = None
    ###### your code here: #####
    result= matrix[::2,:].float().sum(1)
    return result

tensor([[-2.1132,  0.1264,  0.2206,  0.4287,  1.2419,  0.1991],
        [-0.9465, -0.1765, -0.8215, -0.7511, -0.8301, -1.8387],
        [ 0.9447,  1.5673,  0.6037,  1.0576, -0.8645,  1.4010],
        [ 0.5191,  0.0555,  1.0875,  2.0034, -0.9926, -0.3154],
        [-2.5516,  1.1275,  0.2309, -0.0177,  1.3985,  1.3792],
        [ 0.8277,  1.3446, -0.3662, -0.3400,  0.7048, -0.5387],
        [ 1.5372, -1.3131,  1.4332, -0.1671,  0.8736, -1.5214],
        [ 0.9302, -0.2264,  0.8700,  0.9967,  2.0280, -0.0940]])

In [ ]:
a.mean(1).argmax().item()

2

In [ ]:
a.var(correction=0)

tensor(1.1594)

In [ ]:
((a-a.mean())**2).mean()

tensor(1.1594)

In [ ]:
a.softmax(0)

tensor([[0.0084, 0.0718, 0.0830, 0.0875, 0.1668, 0.1030],
        [0.0271, 0.0530, 0.0293, 0.0269, 0.0210, 0.0134],
        [0.1797, 0.3031, 0.1218, 0.1641, 0.0203, 0.3425],
        [0.1174, 0.0668, 0.1976, 0.4225, 0.0179, 0.0615],
        [0.0054, 0.1953, 0.0839, 0.0560, 0.1951, 0.3351],
        [0.1598, 0.2426, 0.0462, 0.0406, 0.0975, 0.0492],
        [0.3250, 0.0170, 0.2792, 0.0482, 0.1154, 0.0184],
        [0.1771, 0.0504, 0.1590, 0.1544, 0.3661, 0.0768]])

In [ ]:
a.sum(0)

tensor([-0.8524,  2.5053,  3.2583,  3.2105,  3.5596, -1.3290])

In [ ]:
A=torch.tensor([[[1, 2],
         [3, 4]],
        [[5, 6],
         [7, 8]]])

B=torch.tensor([[[ 0, 10],
         [20,  0]],
        [[ 0,  0],
         [ 0,  0]]])

In [ ]:
A=torch.rot90(A, 3, [ 0, 1])
A

tensor([[[5, 6],
         [1, 2]],

        [[7, 8],
         [3, 4]]])

In [ ]:
(A*B).sum()

tensor(80)

In [ ]:
B

tensor([[[-1.0956, -0.5428,  0.9674],
         [ 0.7400, -0.7127, -0.6854],
         [ 0.5580,  1.1723,  0.4052]],

        [[ 1.1603,  2.6520,  0.6780],
         [ 0.6383, -1.0605,  0.6840],
         [-1.3008,  0.6684, -0.8342]],

        [[-1.1740, -1.1961, -0.5599],
         [-0.9667,  1.1760, -1.9624],
         [-0.7864,  1.1397,  1.8764]]])

In [ ]:
x=torch.tensor([[ 2,  0,  4],
        [ 4,  2,  8],
        [ 6,  4, 12]]).float()

In [ ]:
x-x.mean(0))

tensor([[-2., -2., -4.],
        [ 0.,  0.,  0.],
        [ 2.,  2.,  4.]])

In [ ]:
torch.cat((torch.ones(3,1),x),1)

tensor([[ 1.,  2.,  0.,  4.],
        [ 1.,  4.,  2.,  8.],
        [ 1.,  6.,  4., 12.]])

In [21]:
X=torch.tensor([[1, 0],
        [0, 1],
        [1, 1]])
y=torch.tensor([1, 2, 3])
w=torch.tensor([-0.3333, -0.3333])

In [42]:


def linear_regression_step(
    X: torch.Tensor, y: torch.Tensor, w: torch.Tensor, lr: float
) -> torch.Tensor:
    """
    Perform one gradient descent step for linear regression MSE.

    Args:
        X (torch.Tensor): Input matrix of shape [N, D].
        y (torch.Tensor): Target tensor of shape [N].
        w (torch.Tensor): Weight tensor of shape [D].
        lr (float): Learning rate.

    Returns:
        torch.Tensor: Updated weights of shape [D].
    """
    ###### your code here: #####
    X = X.float()
    y = y.float()
    w = w.float()
    N=X.shape[0]
    predictions = torch.matmul(X, w)

    grad= 2/N * X.transpose(0,1)@(X@w.view(w.shape,1)-y)
    w+=-lr*grad
    return w


RuntimeError: expected scalar type Long but found Float

In [44]:
torch.matmul(X.float(),w.float())

tensor([-0.4666, -0.4666, -0.9333])

In [38]:
X.shape

torch.Size([3, 2])

In [39]:
w.shape

torch.Size([2])