<a href="https://colab.research.google.com/github/Nurdaylight/Study/blob/main/Tensorgym.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
z=torch.randint(0,2,(9,4))

In [ ]:
z

tensor([[1, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 1, 1, 0],
        [1, 0, 0, 0]])

In [ ]:
b = z <= 0
(b.float()).mean(1).max()

tensor(0.7500)

In [ ]:
b = z==0
a=(b.float()).mean(0).max()
c = (b.float()).mean(0) ==a

result =z[:,c]

In [ ]:
import torch

def drop_column(A: torch.tensor) -> torch.tensor:
    """
    Drops the column of A containing the most 0 values.

    Parameters:
        tensor: A 2D tensor.
    Returns:
        tensor: The input tensor with the column containing the most 0 values removed.
    """

    result = None
    b = A==0
    a=(b.float()).mean(0).max()
    z = (b.float()).mean(0)!=a

    result =A[:,z]
    return result

tensor reshaepe and transpoe

In [ ]:
import torch

def solution(x: torch.Tensor) -> torch.Tensor:
    '''
        x is one-dimentional tensor
    '''
    result = None
    n=len(x)
    result=x.view(-1,int(n/2)).T
    ###### your code here: #####
    return result

just every second row sum

In [ ]:
a=torch.randn(8,6)

In [ ]:
a[::2, :]

tensor([[-2.1132,  0.1264,  0.2206,  0.4287,  1.2419,  0.1991],
        [ 0.9447,  1.5673,  0.6037,  1.0576, -0.8645,  1.4010],
        [-2.5516,  1.1275,  0.2309, -0.0177,  1.3985,  1.3792],
        [ 1.5372, -1.3131,  1.4332, -0.1671,  0.8736, -1.5214]])

In [ ]:
import torch

def solution(matrix: torch.Tensor) -> torch.Tensor:
    result = None
    ###### your code here: #####
    result= matrix[::2,:].float().sum(1)
    return result

tensor([[-2.1132,  0.1264,  0.2206,  0.4287,  1.2419,  0.1991],
        [-0.9465, -0.1765, -0.8215, -0.7511, -0.8301, -1.8387],
        [ 0.9447,  1.5673,  0.6037,  1.0576, -0.8645,  1.4010],
        [ 0.5191,  0.0555,  1.0875,  2.0034, -0.9926, -0.3154],
        [-2.5516,  1.1275,  0.2309, -0.0177,  1.3985,  1.3792],
        [ 0.8277,  1.3446, -0.3662, -0.3400,  0.7048, -0.5387],
        [ 1.5372, -1.3131,  1.4332, -0.1671,  0.8736, -1.5214],
        [ 0.9302, -0.2264,  0.8700,  0.9967,  2.0280, -0.0940]])

In [ ]:
a.mean(1).argmax().item()

2

In [ ]:
a.var(correction=0)

tensor(1.1594)

In [ ]:
((a-a.mean())**2).mean()

tensor(1.1594)

In [ ]:
a.softmax(0)

tensor([[0.0084, 0.0718, 0.0830, 0.0875, 0.1668, 0.1030],
        [0.0271, 0.0530, 0.0293, 0.0269, 0.0210, 0.0134],
        [0.1797, 0.3031, 0.1218, 0.1641, 0.0203, 0.3425],
        [0.1174, 0.0668, 0.1976, 0.4225, 0.0179, 0.0615],
        [0.0054, 0.1953, 0.0839, 0.0560, 0.1951, 0.3351],
        [0.1598, 0.2426, 0.0462, 0.0406, 0.0975, 0.0492],
        [0.3250, 0.0170, 0.2792, 0.0482, 0.1154, 0.0184],
        [0.1771, 0.0504, 0.1590, 0.1544, 0.3661, 0.0768]])

In [ ]:
a.sum(0)

tensor([-0.8524,  2.5053,  3.2583,  3.2105,  3.5596, -1.3290])

In [ ]:
A=torch.tensor([[[1, 2],
         [3, 4]],
        [[5, 6],
         [7, 8]]])

B=torch.tensor([[[ 0, 10],
         [20,  0]],
        [[ 0,  0],
         [ 0,  0]]])

In [ ]:
A=torch.rot90(A, 3, [ 0, 1])
A

tensor([[[5, 6],
         [1, 2]],

        [[7, 8],
         [3, 4]]])

In [ ]:
(A*B).sum()

tensor(80)

In [ ]:
B

tensor([[[-1.0956, -0.5428,  0.9674],
         [ 0.7400, -0.7127, -0.6854],
         [ 0.5580,  1.1723,  0.4052]],

        [[ 1.1603,  2.6520,  0.6780],
         [ 0.6383, -1.0605,  0.6840],
         [-1.3008,  0.6684, -0.8342]],

        [[-1.1740, -1.1961, -0.5599],
         [-0.9667,  1.1760, -1.9624],
         [-0.7864,  1.1397,  1.8764]]])

In [ ]:
x=torch.tensor([[ 2,  0,  4],
        [ 4,  2,  8],
        [ 6,  4, 12]]).float()

In [ ]:
x-x.mean(0))

tensor([[-2., -2., -4.],
        [ 0.,  0.,  0.],
        [ 2.,  2.,  4.]])

In [ ]:
torch.cat((torch.ones(3,1),x),1)

tensor([[ 1.,  2.,  0.,  4.],
        [ 1.,  4.,  2.,  8.],
        [ 1.,  6.,  4., 12.]])

In [21]:
X=torch.tensor([[1, 0],
        [0, 1],
        [1, 1]])
y=torch.tensor([1, 2, 3])
w=torch.tensor([-0.3333, -0.3333])

In [42]:


def linear_regression_step(
    X: torch.Tensor, y: torch.Tensor, w: torch.Tensor, lr: float
) -> torch.Tensor:
    """
    Perform one gradient descent step for linear regression MSE.

    Args:
        X (torch.Tensor): Input matrix of shape [N, D].
        y (torch.Tensor): Target tensor of shape [N].
        w (torch.Tensor): Weight tensor of shape [D].
        lr (float): Learning rate.

    Returns:
        torch.Tensor: Updated weights of shape [D].
    """
    ###### your code here: #####
    X = X.float()
    y = y.float()
    w = w.float()
    N=X.shape[0]
    predictions = torch.matmul(X, w)

    grad= 2/N * X.transpose(0,1)@(X@w.view(w.shape,1)-y)
    w+=-lr*grad
    return w


RuntimeError: expected scalar type Long but found Float

In [44]:
import torch


def logistic_regression_predict(
    X: torch.Tensor, w: torch.Tensor, b: float
) -> (torch.Tensor, torch.Tensor):
    """
    Compute logistic regression probabilities and binary predictions.

    Args:
        X (torch.Tensor): Input matrix of shape [N, D].
        w (torch.Tensor): Weight tensor of shape [D].
        b (float): Bias scalar.

    Returns:
        (torch.Tensor, torch.Tensor): Probabilities and binary predictions.
    """
    ###### your code here: #####
    X=X.float()
    w=w.float()

    logits=torch.sigmoid(X@w+b)
    classes= logits>=0.5

    return logits, classes


tensor([-0.4666, -0.4666, -0.9333])

In [38]:
X.shape

torch.Size([3, 2])

In [45]:
import torch
import torch.nn.functional as F

In [109]:
q=torch.tensor([[1., 2.],
        [2., 1.]])

k=torch.tensor([[1., 0.],
        [0., 1.]])

val=torch.tensor([[2., 0.],
        [0., 4.]])
mask=torch.tensor([[1, 1],
        [1, 0]])




In [163]:
import torch
import torch.nn.functional as F


def masked_attention(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    mask: torch.Tensor,
) -> torch.Tensor:
    """
    Compute masked scaled dot-product attention.

    Args:
        query (torch.Tensor): Query tensor of shape [T, d_k].
        key (torch.Tensor): Key tensor of shape [T, d_k].
        value (torch.Tensor): Value tensor of shape [T, d_v].
        mask (torch.Tensor): Attention mask of shape [T, T] with 1 for valid positions and 0 for masked positions.

    Returns:
        torch.Tensor: Attention output of shape [T, d_v].
    """
    ###### your code here: #####
    q=query
    k=key

    z=(q@k.transpose(0,1))/torch.sqrt(torch.tensor(k.shape[1]))
    z=z.masked_fill(mask==0, float('-inf'))
    z
    value=F.softmax(z,1)@value
    return value


In [86]:
z

tensor([[0.7071, 0.0000],
        [1.4142, 0.0000]])

In [87]:
z.max(0)[0]

tensor([1.4142, 0.0000])

In [88]:
z.mean(0)

tensor([1.0607, 0.0000])

In [95]:
z.diag().prod()

tensor(0.)

In [113]:
k.unsqueeze(-1).shape

torch.Size([2, 2, 1])

In [106]:
z

torch.Size([2, 1, 2])

In [115]:
logits=torch.tensor([[ 0.,  0.,  0.],
        [ 1.,  2., -1.]])

In [130]:
torch.exp(logits)/(torch.exp(logits)).sum(1,keepdim=True)
torch.exp(logits)/(torch.exp(logits)).sum(1,keepdim=True)

tensor([[0.3333, 0.3333, 0.3333],
        [0.2595, 0.7054, 0.0351]])

In [145]:
z.view(2,2).mean(1)

tensor([0.3536, 0.7071])

In [144]:
z

tensor([[[0.7071, 0.0000]],

        [[1.4142, 0.0000]]])

In [147]:
1.0127/0.9877

1.0253113293510174

In [158]:
oo=torch.tensor([[10.,  4.],
        [ 4.,  2.],
        [ 6.,  0.]])
oo= oo-oo.mean(1,keepdim=True)
oo

tensor([[ 3., -3.],
        [ 1., -1.],
        [ 3., -3.]])

In [162]:
oo.var(0,correction=1, keepdim=True)

tensor([[1.3333, 1.3333]])

In [159]:
torch.var(oo, dim=0)

tensor([1.3333, 1.3333])

Below is simple attention mechanism code

In [165]:
query=torch.tensor([[1., 0.],
        [0., 1.]])

In [166]:
key=torch.tensor([[1., 1.],
        [0., 0.]])

In [167]:
value=torch.tensor([[2., 2.],
        [3., 3.]])

In [175]:

import torch
import math
import torch.nn.functional as F

def attention(query: torch.Tensor, key: torch.Tensor, value: torch.Tensor) -> torch.Tensor:
    result = None
    ###### your code here: #####
    return F.softmax(query@key.transpose(0,1)/torch.sqrt(torch.tensor(key.shape[1])),1)@value

In [176]:
x=torch.tensor([[ 0.5000, -0.5000,  1.5000]])

In [180]:


class CustomReLUFunction(autograd.Function):
    @staticmethod
    def forward(ctx, x):
        """
        Forward pass for the ReLU activation function.
        """
        # Save the input tensor 'x' for use in the backward pass
        ctx.save_for_backward(x)
        return torch.max(x, torch.zeros_like(x))

    @staticmethod
    def backward(ctx, grad_output):
        """
        Backward pass for the ReLU activation function.
        """
        # Retrieve the saved input tensor
        input_x, = ctx.saved_tensors

        # Cloning is necessary because directly modifying grad_output could affect other
        # parts of the computational graph that are using this tensor.
        grad_input = grad_output.clone()

        # The derivative of ReLU is 1 where input > 0
        grad_input[input_x > 0] *= 1
        # The derivative of ReLU is 0 where input <= 0
        grad_input[input_x <= 0] *= 0
        return grad_input


def compute_custom_relu(input_tensor: torch.Tensor) -> (torch.Tensor, torch.Tensor):
    """
    Apply the CustomReLUFunction to the input tensor and compute the gradient.


tensor([[0.5000, 0.0000, 1.5000]])

In [214]:
x

tensor([[0.5000, 7.0000, 1.5000]])

In [242]:

x[x <= 7] -= 1
x

tensor([[1.5000, 8.0000, 1.5000]])

In [260]:
b=torch.tensor([[[ 0, 10],
         [20,  0]],

        [[ 0,  0],
         [ 0,  0]]])

In [243]:
a=torch.tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [269]:
a[:,0,:]

tensor([[1, 2],
        [5, 6]])

In [248]:
(a

tensor(80)

In [279]:
x=max[a.rot90(dims=[0,1])*b).sum()]

tensor(180)

In [281]:
#rotation parameters for moving each cube face to the top of the cube
rots = [{'k':0, 'dims':[0,1]}, {'k':1, 'dims':[0,1]}, {'k':2, 'dims':[0,1]},
      {'k':3, 'dims':[0,1]}, {'k':1, 'dims':[0,2]},{'k':-1, 'dims':[0,2]}]
each_face_on_top = [a.rot90(**r) for r in rots]

#for each of the six possible faces on top, perform the four rotations fixing the top face
all_rotations = [X.rot90(k,[1,2]) for X,k in product(each_face_on_top, range(4))]

result = max([(X*b).sum() for X in all_rotations])
result

tensor(210)

In [282]:
[(X*b).sum() for X in all_rotations]

[tensor(80),
 tensor(60),
 tensor(70),
 tensor(90),
 tensor(180),
 tensor(140),
 tensor(150),
 tensor(190),
 tensor(180),
 tensor(200),
 tensor(210),
 tensor(190),
 tensor(80),
 tensor(120),
 tensor(130),
 tensor(90),
 tensor(140),
 tensor(120),
 tensor(160),
 tensor(180),
 tensor(150),
 tensor(130),
 tensor(90),
 tensor(110)]

In [283]:
x=torch.tensor([[ 1.0000,  1.0000,  0.0000,  6.0000],
        [ 2.0000,  2.0000,  1.0000,  1.5000],
        [ 5.0000,  0.0000, -1.0000,  1.0000],
        [-1.0000,  0.0000,  1.0000,  1.0000]])

In [284]:
a=4
b=4
c=1

In [ ]:
# Copied and simplified from official https://github.com/microsoft/LoRA
# Try solving on your own without looking at the original sources

import torch
import torch.nn as nn
import torch.nn.functional as F


class LoRALinear(nn.Linear):
    # LoRA implemented in a dense layer
    def __init__(
        self,
        in_features: int,
        out_features: int,
        r: int = 0,
        lora_alpha: int = 1,
        lora_dropout: float = 0.1,
        **kwargs
    ):
        nn.Linear.__init__(self, in_features, out_features, **kwargs)

        self.lora_dropout = nn.Dropout(p=lora_dropout)
        # Mark the weight as unmerged
        self.merged = False
        self.r = r

        # Actual trainable parameters
        if r > 0:
            self.lora_A = nn.Parameter(self.weight.new_zeros((r, in_features)))
            self.lora_B = nn.Parameter(self.weight.new_zeros((out_features, r)))
            self.scaling = lora_alpha / self.r
            # Freezing the pre-trained weight matrix
            self.weight.requires_grad = False
        self.reset_parameters()


    def forward(self, x: torch.Tensor):
        """
        Performs the forward pass through the layer, incorporating LoRA adaptation if enabled.

        Args:
            x (torch.Tensor): The input tensor to the layer.

        Returns:
            torch.Tensor: The output tensor after applying the layer's operations.
        """

        # If LoRA adaptation is enabled and not merged:
        if self.r > 0 and not self.merged:

            # Apply the initial linear transformation using the base layer's weights
            transformed = F.linear(x, self.weight, bias=self.bias)

            # Apply dropout to the input.
            # Then multiply the dropout-applied input with the transposed lora_A matrix,
            # and then with the transposed lora_B matrix.
            # Then scale the LoRA adaptation and add it to the original transformation.
            ###### your code here: #####
            lA=self.lora_dropout(x) @ self.lora_A.T @self.lora_B.T
            result = lA*self.scaling+transformed
            return result

        else:
            # Simply apply the base linear layer without LoRA modifications
            return F.linear(x, self.weight, bias=self.bias)




def compute_lora_linear(x: torch.Tensor, in_features: int, out_features: int, rank: int) -> torch.Tensor:
    torch.manual_seed(0)  # Ensure reproducibility
    model = LoRALinear(in_features, out_features, rank)

    # Simulate training by initializing lora_A and lora_B with non-zero values
    # Normally, these values would be learned during the training process
    with torch.no_grad():
        model.lora_A.copy_(torch.randn_like(model.lora_A))
        model.lora_B.copy_(torch.randn_like(model.lora_B))

    return model.forward(x)