In [1]:
import sys
sys.executable

'C:\\Users\\user\\torch310\\Scripts\\python.exe'

In [9]:
import torch

In [3]:
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.9.1+cpu
CUDA available: False


In [8]:
device = torch.device("cpu")  # Force CPU
x = torch.randn(3, 3, device=device)
print(x)

tensor([[ 1.0856,  0.0784,  0.9766],
        [-0.3301, -0.4981, -0.3082],
        [-1.6517,  1.2659,  0.7712]])


In [10]:
import numpy as np

In [11]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [14]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6386, 0.5836],
        [0.1050, 0.4630]]) 

